# Generated by Django 5.0.6 on 2024-07-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_analysis', models.FileField(blank=True, upload_to='docs/')),
                ('report_analysis', models.FileField(blank=True, upload_to='report_docs/')),
            ],
        ),
    ]
