# Generated by Django 4.2.13 on 2024-07-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_lattitude', models.BigIntegerField()),
                ('receiver_longitude', models.BigIntegerField()),
                ('receiver_antenna_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmitter_name', models.CharField(max_length=50)),
                ('lattitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('antenna_height', models.IntegerField()),
            ],
        ),
    ]
